name: build
on: [ push ]
permissions:
  contents: write
jobs:
  netboot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v12
    - uses: DeterminateSystems/magic-nix-cache-action@v7
    - run: |
        nix build -vL
        cp -Lr --no-preserve=all result artifact
        sed -e "s|^kernel bzImage|kernel http://github.com/NickCao/netboot/releases/download/latest/bzImage|" \
            -e "s|^initrd initrd|initrd http://github.com/NickCao/netboot/releases/download/latest/initrd|" \
            -i artifact/ipxe
    - uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        tag_name: latest
        files: |
          artifact/ipxe
          artifact/initrd
          artifact/bzImage
