name: build
on: [ push ]
permissions:
  id-token: write
jobs:
  netboot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v14
    - uses: DeterminateSystems/magic-nix-cache-action@v8
    - run: |
        nix build -vL
        cp -Lr --no-preserve=all result artifact
        sed -e "s|^kernel bzImage|kernel https://github.com/NickCao/netboot/releases/download/latest/bzImage|" \
            -e "s|^initrd initrd|initrd https://github.com/NickCao/netboot/releases/download/latest/initrd|" \
            -i artifact/ipxe
    - uses: actions/upload-pages-artifact@v3
      with:
        path: artifact
    - uses: actions/deploy-pages@v4
