name: build
on: [ push ]
permissions:
  id-token: write
  pages: write
jobs:
  netboot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v14
    - uses: DeterminateSystems/magic-nix-cache-action@v8
    - run: |
        nix build -vL
        cp -Lr --no-preserve=all result artifact
    - uses: actions/upload-pages-artifact@v3
      with:
        path: artifact
    - uses: actions/deploy-pages@v4
