name: build
on: [ push ]
permissions:
  id-token: write
  pages: write
jobs:
  netboot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v14
    - uses: DeterminateSystems/magic-nix-cache-action@v8
    - run: |
        nix build -vL
        cp -Lr --no-preserve=all result artifact
        ln -sr artifact/{ipxe,index.html}
    - run: |
        sudo apt-get install -y qemu-kvm

        cat <<EOF > bootfile
        #!ipxe
        # shutdown now
        set cmdline script="https://httpbin.org/base64/c2h1dGRvd24gbm93Cg=="
        chain result/ipxe
        EOF

        systemd-run --user --unit=netboot-test --wait --same-dir --remain-after-exit \
          --property=MemoryAccounting=yes --property=RuntimeMaxSec=120 \
          qemu-system-x86_64 -M q35 -enable-kvm -cpu host -smp 2 -m 2G \
          -boot order=n -nic user,tftp=.,bootfile=bootfile -display none

        echo "::notice title=status::$(systemctl status --user netboot-test)"
    - uses: actions/upload-pages-artifact@v3
      with:
        path: artifact
    - uses: actions/deploy-pages@v4
