name: build
on: [ push ]
jobs:
  netboot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - run: |
        nix build -vL .#hydraJobs.netboot
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        files: |
          result/ipxe
          result/initrd
          result/bzImage
