name: build
on: [ push ]
jobs:
  netboot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - run: |
        nix build -vL .#hydraJobs.netboot
